version: '3.8'

services:
  api:
    build: .
    ports:
        - 5000:5000
  postgres:
    image: postgres
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    ports:
        - "5432:5432"