@startuml
title Architecture

cloud Procore
cloud GoogleCalendar

node DatabaseNode {
    database Database
    [DataMapper] --> Database
}

node WebView
node EmailView

node Interactor {
    [Entites] <-- [DataMapper]
    DataGateway <|-- [DataMapper]
    UseCaseInput <-- [Controller]
    [UseCaseInteractor] --|> UseCaseInput
    UseCaseOutput <-- [UseCaseInteractor]
    [UseCaseInteractor] --> [Entites]
    [UseCaseInteractor] --> DataGateway
}

node Controller {
    Procore --> [RequestHandler]
    WebView --> [RequestHandler]
    [RequestHandler] --> [Controller]
    [Presenter] --> [WebViewModel]
    [Presenter] --> [GCalViewModel]
    [Presenter] --> [EmailViewModel]
    [EmailViewModel] --> EmailView
    [WebViewModel] <-- WebView
    [GCalViewModel] --> GoogleCalendar
    UseCaseOutput <|-- [Presenter]
}



@enduml