@startuml
title Database

entity User {
    * id : key
    ---
    * email : string
    * displayName : string
}

entity Oauth2Token {
    * id : key
    ---
    * token : string
    * refresh_token : string
    * token_type : string
    * expires_at : int
}

entity AccountManager {
    * id : key
    ---
    * user_id : foreign_key
    * is_trial : bool
    * trial_start : datetime
    * payment_id : uuid
    * org_id : string
}

entity Collaborator {
    * id : key
    ---
    * user_id : foreign_key
    * manager_id : foreign_key
}

entity ProcoreSettings {
    * id : key
    ---
    * manager_id : foreign_key
    * token_id : foreign_key
}

entity CalendarSettings {
    * id : key
    ---
    * user_id : foreign_key
    * token_id : foreign_key
    * google_calendar_id: string
}

entity ApplicationSettings {
    * id : key
    ---
    * monthly_price : int
    * trial_period : timespan
}

entity EmailSettings {
    * id : key
    ---
    * user_id : foreign_key
    * eventChange : bool
    * addCollaborator : bool
}

AccountManager ||-- ProcoreSettings
User ||-- AccountManager
User ||-- CalendarSettings
User ||-- Collaborator
AccountManager }|-- Collaborator
ProcoreSettings ||-- Oauth2Token
CalendarSettings ||-- Oauth2Token

@enduml