@startuml
title Database

entity User {
    * id : key
    ---
    * email : string
    * displayName : string
}

entity Oauth2Token {
    * id : key
    ---
    * token : string
    * refresh_token : string
    * token_type : string
    * expires_at : int
}

entity AccountManager {
    * id : key
    ---
    * user_id : foreign_key
    * procore_settings_id: foreign_key
    * gcal_settings_id: foreign_key
    * is_trial : bool
    * trial_start : datetime
    * payment_id : uuid
    * project_id : int
}

entity Collaborator {
    * id : key
    ---
    * user_id : foreign_key
    * manager_id : foreign_key
    * gcal_settings_id: foreign_key
}

entity ProcoreSettings {
    * id : key
    ---
    * token_id : foreign_key
}

entity CalendarSettings {
    * id : key
    ---
    * token_id : foreign_key
    * google_calendar_id: string
}

entity ApplicationSettings {
    * id : key
    ---
    * monthly_price : int
    * trial_period : timespan
}

entity EmailSetting {
    * id : key
    ---
    * name : string
}

entity EventType {
    * id : key
    ---
    * procore_id : string
    * name : string
}

entity UserEmailSetting {
    * id : key
    ---
    * setting_id : foreign_key
    * user_id : foreign_key
    * enabled : bool
}

entity UserEventType {
    * id : key
    ---
    * event_id : foreign_key
    * user_id : foreign_key
    * enabled : bool
}

AccountManager ||-- ProcoreSettings
User ||-- AccountManager
User ||-- CalendarSettings
User ||-- Collaborator
AccountManager }|-- Collaborator
ProcoreSettings ||-- Oauth2Token
CalendarSettings ||-- Oauth2Token
AccountManager }|-- UserEmailSetting
AccountManager }|-- UserEventType
UserEventType ||-- EventType
UserEmailSetting ||-- EmailSetting

@enduml