@startuml
title Sequence

actor Customer
actor Collaborator
participant Procore
boundary Application
database DB
participant GoogleCalendar
participant Stripe
participant EmailService

Customer -> Procore : Install app
Procore -> Application : Install command
Application -> Procore : Notify link
Customer -> Procore : View link
Customer -> Application : Follow link/get code
Customer -> Procore : Enter code
Procore -> Application : Verify code
Application -> DB : Save user
Application -> EmailService : Send email

newpage

Customer -> Application : Sign up
Application -> Procore : Oauth
Customer -> Application : Payment info
Application -> Stripe : Authenticate credit card
Application -> DB : Register user
Application -> EmailService : Send confirmation

newpage

Customer -> Procore : Add/modify/delete event
Procore -> Application : Webhooks
Application -> GoogleCalendar : Add/modify/delete event
Customer -> GoogleCalendar : View event

newpage

Customer -> Application : Modify settings
Application -> DB : Update settings

newpage

Customer -> Application : Subscribe
Customer -> Application : Payment info
Application -> Stripe : Authenticate payment info
Stripe -> Application : API Credentials
Application -> DB : Update user
Application -> EmailService : Notify user

newpage

Application -> DB : Check subscription info
Application <- DB : Time to bill
Application -> Stripe : Bill customer
Application -> EmailService : Send notification

newpage

Customer -> Application : Add collaborator
Application -> EmailService : Send request
EmailService -> Collaborator : Send auth link
Collaborator -> Application : Click GCal Oauth link
Application -> GoogleCalendar : Oauth
GoogleCalendar -> Application : Notify auth
Application -> DB : Update user

@enduml