@startuml
title Sequence

actor Customer
participant Procore
boundary Application
database DB
participant GoogleCalendar
participant Stripe
participant EmailService

Customer -> Procore : Install app
Procore -> Application : Register user
Application -> DB : Save user
Application -> EmailService : Send confirmation
Application -> Procore : Notify link
Procore -> Customer : Share link
Customer -> Application : Visit link
Application -> Customer : Present credentials
Customer -> Procore : Enter credentials

newpage

Customer -> Application : Sign up
Customer -> Application : Payment info
Application -> Stripe : Authenticate credit card
Application -> DB : Register user
Application -> EmailService : Send confirmation

newpage

Customer -> Procore : Add/modify/delete event
Procore -> Application : Webhooks
Application -> GoogleCalendar : Add/modify/delete event
Customer -> GoogleCalendar : View event

newpage

Customer -> Application : Modify settings
Application -> DB : Update settings

newpage

Customer -> Application : Subscribe
Customer -> Application : Payment info
Application -> Stripe : Authenticate payment info
Stripe -> Application : API Credentials
Application -> Database : Update user
Application -> EmailService : Notify user

newpage

Application -> DB : Check subscription info
Application <- DB : Time to bill
Application -> Stripe : Bill customer
Application -> EmailService : Send notification

@enduml